"""Audited official model capability catalog for CODE-012 C2."""

CATALOG_JSON = r'''{
  "schema": "code-official-model-capabilities/v1",
  "catalogRevision": "2026-08-21.c1",
  "verifiedAt": "2026-08-21",
  "entries": [
    {
      "provider": "openai",
      "modelId": "gpt-5.6-sol",
      "aliases": [{"id": "gpt-5.6", "moving": true, "maxAgeDays": 7}],
      "contextWindowTokens": 1050000,
      "maxOutputTokens": 128000,
      "sourceUrl": "https://developers.openai.com/api/docs/models/gpt-5.6-sol",
      "asOf": "2026-08-21",
      "confidence": "official_direct",
      "status": "active",
      "maxAgeDays": 30,
      "aliasAmbiguity": "moving-official-alias",
      "conditions": ["The gpt-5.6 alias currently routes to gpt-5.6-sol."]
    },
    {
      "provider": "openai",
      "modelId": "gpt-5.6-terra",
      "aliases": [],
      "contextWindowTokens": 1050000,
      "maxOutputTokens": 128000,
      "sourceUrl": "https://developers.openai.com/api/docs/models",
      "asOf": "2026-08-21",
      "confidence": "official_direct",
      "status": "active",
      "maxAgeDays": 30,
      "aliasAmbiguity": "none",
      "conditions": []
    },
    {
      "provider": "openai",
      "modelId": "gpt-5.6-luna",
      "aliases": [],
      "contextWindowTokens": 1050000,
      "maxOutputTokens": 128000,
      "sourceUrl": "https://developers.openai.com/api/docs/models",
      "asOf": "2026-08-21",
      "confidence": "official_direct",
      "status": "active",
      "maxAgeDays": 30,
      "aliasAmbiguity": "none",
      "conditions": []
    },
    {
      "provider": "openai",
      "modelId": "gpt-5.4",
      "aliases": [],
      "contextWindowTokens": 1050000,
      "maxOutputTokens": 128000,
      "sourceUrl": "https://developers.openai.com/api/docs/models/gpt-5.4",
      "asOf": "2026-08-21",
      "confidence": "official_direct",
      "status": "active",
      "maxAgeDays": 30,
      "aliasAmbiguity": "none",
      "conditions": ["Long-context pricing applies above 272K input tokens."]
    },
    {
      "provider": "openai",
      "modelId": "gpt-5.4-mini",
      "aliases": [{"id": "gpt-5.4-mini-2026-03-17", "moving": false}],
      "contextWindowTokens": 400000,
      "maxOutputTokens": 128000,
      "sourceUrl": "https://developers.openai.com/api/docs/models/gpt-5.4-mini",
      "asOf": "2026-08-21",
      "confidence": "official_direct",
      "status": "active",
      "maxAgeDays": 30,
      "aliasAmbiguity": "none",
      "conditions": []
    },
    {
      "provider": "openai",
      "modelId": "gpt-5.3-codex",
      "aliases": [],
      "contextWindowTokens": 400000,
      "maxOutputTokens": 128000,
      "sourceUrl": "https://developers.openai.com/api/docs/models/gpt-5.3-codex",
      "asOf": "2026-08-21",
      "confidence": "official_direct",
      "status": "active",
      "maxAgeDays": 30,
      "aliasAmbiguity": "none",
      "conditions": ["Coding-optimized model variant."]
    },
    {
      "provider": "openai",
      "modelId": "gpt-5.2-codex",
      "aliases": [],
      "contextWindowTokens": 400000,
      "maxOutputTokens": 128000,
      "sourceUrl": "https://developers.openai.com/api/docs/models/gpt-5.2-codex",
      "asOf": "2026-08-21",
      "confidence": "official_direct",
      "status": "active",
      "maxAgeDays": 30,
      "aliasAmbiguity": "none",
      "conditions": ["Coding-optimized model variant."]
    },
    {
      "provider": "openai",
      "modelId": "gpt-5.1-codex",
      "aliases": [],
      "contextWindowTokens": 400000,
      "maxOutputTokens": 128000,
      "sourceUrl": "https://developers.openai.com/api/docs/models/gpt-5.1-codex",
      "asOf": "2026-08-21",
      "confidence": "official_direct",
      "status": "active",
      "maxAgeDays": 30,
      "aliasAmbiguity": "deprecated",
      "conditions": ["Deprecated; official narrative describes Responses API availability."]
    },
    {
      "provider": "openai",
      "modelId": "gpt-4.1",
      "aliases": [{"id": "gpt-4.1-2025-04-14", "moving": false}],
      "contextWindowTokens": 1047576,
      "maxOutputTokens": 32768,
      "sourceUrl": "https://developers.openai.com/api/docs/models/gpt-4.1",
      "asOf": "2026-08-21",
      "confidence": "official_direct",
      "status": "active",
      "maxAgeDays": 30,
      "aliasAmbiguity": "none",
      "conditions": []
    },
    {
      "provider": "anthropic",
      "modelId": "claude-opus-5",
      "aliases": [],
      "contextWindowTokens": 1000000,
      "maxOutputTokens": 128000,
      "sourceUrl": "https://platform.claude.com/docs/en/about-claude/models/overview",
      "asOf": "2026-08-21",
      "confidence": "official_direct",
      "status": "active",
      "maxAgeDays": 30,
      "aliasAmbiguity": "none",
      "conditions": ["Dateless Claude 4.6+ IDs are pinned snapshots."]
    },
    {
      "provider": "anthropic",
      "modelId": "claude-sonnet-5",
      "aliases": [],
      "contextWindowTokens": 1000000,
      "maxOutputTokens": 128000,
      "sourceUrl": "https://platform.claude.com/docs/en/about-claude/models/overview",
      "asOf": "2026-08-21",
      "confidence": "official_direct",
      "status": "active",
      "maxAgeDays": 30,
      "aliasAmbiguity": "none",
      "conditions": ["Dateless Claude 4.6+ IDs are pinned snapshots."]
    },
    {
      "provider": "anthropic",
      "modelId": "claude-opus-4-6",
      "aliases": [],
      "contextWindowTokens": 1000000,
      "maxOutputTokens": 128000,
      "sourceUrl": "https://platform.claude.com/docs/en/about-claude/models/migration-guide",
      "asOf": "2026-08-21",
      "confidence": "official_direct",
      "status": "active",
      "maxAgeDays": 30,
      "aliasAmbiguity": "none",
      "conditions": ["Message Batches can use a separate 300K output beta; not applied here."]
    },
    {
      "provider": "anthropic",
      "modelId": "claude-sonnet-4-6",
      "aliases": [],
      "contextWindowTokens": 1000000,
      "maxOutputTokens": 128000,
      "sourceUrl": "https://platform.claude.com/docs/en/about-claude/models/migration-guide",
      "asOf": "2026-08-21",
      "confidence": "official_direct",
      "status": "active",
      "maxAgeDays": 30,
      "aliasAmbiguity": "none",
      "conditions": ["Message Batches can use a separate 300K output beta; not applied here."]
    },
    {
      "provider": "anthropic",
      "modelId": "claude-sonnet-4-5-20250929",
      "aliases": [{"id": "claude-sonnet-4-5", "moving": true, "maxAgeDays": 7}],
      "contextWindowTokens": 200000,
      "maxOutputTokens": null,
      "sourceUrl": "https://platform.claude.com/docs/en/build-with-claude/context-windows",
      "asOf": "2026-08-21",
      "confidence": "official_direct",
      "status": "active",
      "maxAgeDays": 30,
      "aliasAmbiguity": "moving-official-alias",
      "conditions": ["The former 1M beta retired on 2026-04-30."]
    },
    {
      "provider": "anthropic",
      "modelId": "claude-haiku-4-5-20251001",
      "aliases": [{"id": "claude-haiku-4-5", "moving": true, "maxAgeDays": 7}],
      "contextWindowTokens": 200000,
      "maxOutputTokens": 64000,
      "sourceUrl": "https://platform.claude.com/docs/en/about-claude/models/overview",
      "asOf": "2026-08-21",
      "confidence": "official_direct",
      "status": "active",
      "maxAgeDays": 30,
      "aliasAmbiguity": "moving-official-alias",
      "conditions": []
    },
    {
      "provider": "google",
      "modelId": "gemini-3.7-flash",
      "aliases": [],
      "contextWindowTokens": 1048576,
      "maxOutputTokens": 65536,
      "sourceUrl": "https://ai.google.dev/gemini-api/docs/models/gemini-3.7-flash",
      "asOf": "2026-08-21",
      "confidence": "official_direct",
      "status": "active",
      "maxAgeDays": 30,
      "aliasAmbiguity": "none",
      "conditions": ["Stable model; model page last updated 2026-08-13 UTC."]
    },
    {
      "provider": "google",
      "modelId": "gemini-3.5-flash",
      "aliases": [],
      "contextWindowTokens": 1048576,
      "maxOutputTokens": 65536,
      "sourceUrl": "https://ai.google.dev/gemini-api/docs/models/gemini-3.5-flash",
      "asOf": "2026-08-21",
      "confidence": "official_direct",
      "status": "active",
      "maxAgeDays": 30,
      "aliasAmbiguity": "none",
      "conditions": ["Stable model."]
    },
    {
      "provider": "google",
      "modelId": "gemini-2.5-pro",
      "aliases": [],
      "contextWindowTokens": 1048576,
      "maxOutputTokens": 65536,
      "sourceUrl": "https://ai.google.dev/gemini-api/docs/models/gemini-2.5-pro",
      "asOf": "2026-08-21",
      "confidence": "official_direct",
      "status": "active",
      "maxAgeDays": 30,
      "aliasAmbiguity": "none",
      "conditions": ["Stable model."]
    },
    {
      "provider": "google",
      "modelId": "gemini-2.5-flash",
      "aliases": [],
      "contextWindowTokens": 1048576,
      "maxOutputTokens": 65536,
      "sourceUrl": "https://ai.google.dev/gemini-api/docs/models/gemini-2.5-flash",
      "asOf": "2026-08-21",
      "confidence": "official_direct",
      "status": "active",
      "maxAgeDays": 30,
      "aliasAmbiguity": "none",
      "conditions": ["Stable model; retired preview IDs are not aliases."]
    },
    {
      "provider": "google",
      "modelId": "gemini-2.5-flash-lite",
      "aliases": [],
      "contextWindowTokens": 1048576,
      "maxOutputTokens": 65536,
      "sourceUrl": "https://ai.google.dev/gemini-api/docs/models/gemini-2.5-flash-lite",
      "asOf": "2026-08-21",
      "confidence": "official_direct",
      "status": "active",
      "maxAgeDays": 30,
      "aliasAmbiguity": "none",
      "conditions": ["Stable model; retired preview IDs are not aliases."]
    },
    {
      "provider": "xai",
      "modelId": "grok-4.5",
      "aliases": [],
      "contextWindowTokens": 500000,
      "maxOutputTokens": null,
      "sourceUrl": "https://docs.x.ai/developers/models/grok-4.5",
      "asOf": "2026-08-21",
      "confidence": "official_direct",
      "status": "active",
      "maxAgeDays": 30,
      "aliasAmbiguity": "moving-aliases-excluded",
      "conditions": ["grok-4.5-latest and grok-build-latest are excluded moving aliases."]
    },
    {
      "provider": "xai",
      "modelId": "grok-4.3",
      "aliases": [],
      "contextWindowTokens": 1000000,
      "maxOutputTokens": null,
      "sourceUrl": "https://docs.x.ai/developers/models/grok-4.3",
      "asOf": "2026-08-21",
      "confidence": "official_direct",
      "status": "active",
      "maxAgeDays": 30,
      "aliasAmbiguity": "moving-aliases-excluded",
      "conditions": ["grok-latest is excluded because it can migrate."]
    },
    {
      "provider": "xai",
      "modelId": "grok-4.20-0309-reasoning",
      "aliases": [{"id": "grok-4.20-0309-non-reasoning", "moving": false}],
      "contextWindowTokens": 1000000,
      "maxOutputTokens": null,
      "sourceUrl": "https://docs.x.ai/developers/models/grok-4.20",
      "asOf": "2026-08-21",
      "confidence": "official_direct",
      "status": "active",
      "maxAgeDays": 30,
      "aliasAmbiguity": "mode-variants-enumerated",
      "conditions": ["Only the two dated reasoning and non-reasoning variants are enumerated."]
    },
    {
      "provider": "xai",
      "modelId": "grok-build-0.1",
      "aliases": [],
      "contextWindowTokens": 256000,
      "maxOutputTokens": null,
      "sourceUrl": "https://docs.x.ai/developers/models/grok-code-fast-1",
      "asOf": "2026-08-21",
      "confidence": "official_direct",
      "status": "active",
      "maxAgeDays": 30,
      "aliasAmbiguity": "retired-redirect-excluded",
      "conditions": ["The retired grok-code-fast-1 redirect is not treated as a stable alias."]
    },
    {
      "provider": "deepseek",
      "modelId": "deepseek-v4-flash",
      "aliases": [],
      "contextWindowTokens": 1000000,
      "maxOutputTokens": 384000,
      "sourceUrl": "https://api-docs.deepseek.com/quick_start/pricing/",
      "asOf": "2026-08-21",
      "confidence": "official_direct",
      "status": "active",
      "maxAgeDays": 30,
      "aliasAmbiguity": "retired-legacy-aliases-excluded",
      "conditions": ["Thinking and non-thinking modes share the model ID; deepseek-chat and deepseek-reasoner are retired."]
    },
    {
      "provider": "deepseek",
      "modelId": "deepseek-v4-pro",
      "aliases": [],
      "contextWindowTokens": 1000000,
      "maxOutputTokens": 384000,
      "sourceUrl": "https://api-docs.deepseek.com/quick_start/pricing/",
      "asOf": "2026-08-21",
      "confidence": "official_direct",
      "status": "active",
      "maxAgeDays": 30,
      "aliasAmbiguity": "retired-legacy-aliases-excluded",
      "conditions": ["Thinking and non-thinking modes share the model ID; deepseek-chat and deepseek-reasoner are retired."]
    },
    {
      "provider": "kimi",
      "modelId": "kimi-k3",
      "aliases": [],
      "contextWindowTokens": 1000000,
      "maxOutputTokens": 1048576,
      "sourceUrl": "https://platform.kimi.com/docs/guide/kimi-k3-quickstart",
      "asOf": "2026-08-21",
      "confidence": "official_direct",
      "status": "active",
      "maxAgeDays": 30,
      "aliasAmbiguity": "none",
      "conditions": ["max_completion_tokens defaults to 131072 and is still bounded by the remaining total context."]
    },
    {
      "provider": "kimi",
      "modelId": "kimi-k2.7-code",
      "aliases": [{"id": "kimi-k2.7-code-highspeed", "moving": false}],
      "contextWindowTokens": null,
      "maxOutputTokens": null,
      "officialLabel": "256K",
      "sourceUrl": "https://platform.kimi.com/docs/api/models-overview",
      "asOf": "2026-08-21",
      "confidence": "official_label_only",
      "status": "research_pending",
      "maxAgeDays": 30,
      "aliasAmbiguity": "same-model-speed-variant",
      "conditions": ["The official source does not define whether 256K means 256000 or 262144 tokens."]
    },
    {
      "provider": "kimi",
      "modelId": "kimi-k2.6",
      "aliases": [],
      "contextWindowTokens": null,
      "maxOutputTokens": null,
      "officialLabel": "256K",
      "sourceUrl": "https://platform.kimi.com/docs/models",
      "asOf": "2026-08-21",
      "confidence": "official_label_only",
      "status": "research_pending",
      "maxAgeDays": 30,
      "aliasAmbiguity": "none",
      "conditions": ["The official source does not define whether 256K means 256000 or 262144 tokens."]
    },
    {
      "provider": "kimi",
      "modelId": "kimi-k2.5",
      "aliases": [],
      "contextWindowTokens": null,
      "maxOutputTokens": null,
      "officialLabel": "256K",
      "sourceUrl": "https://platform.kimi.com/docs/models",
      "asOf": "2026-08-21",
      "confidence": "official_label_only",
      "status": "research_pending",
      "maxAgeDays": 7,
      "aliasAmbiguity": "scheduled-retirement",
      "validUntil": "2026-08-31",
      "conditions": ["Closed to new users and scheduled for platform retirement on 2026-08-31."]
    },
    {
      "provider": "kimi",
      "modelId": "moonshot-v1-8k",
      "aliases": [],
      "contextWindowTokens": null,
      "maxOutputTokens": null,
      "officialLabel": "8K",
      "sourceUrl": "https://platform.kimi.com/docs/models",
      "asOf": "2026-08-21",
      "confidence": "official_label_only",
      "status": "research_pending",
      "maxAgeDays": 7,
      "aliasAmbiguity": "scheduled-retirement",
      "validUntil": "2026-08-31",
      "conditions": ["The official label combines input and output and the model is scheduled for retirement on 2026-08-31."]
    },
    {
      "provider": "kimi",
      "modelId": "moonshot-v1-32k",
      "aliases": [],
      "contextWindowTokens": null,
      "maxOutputTokens": null,
      "officialLabel": "32K",
      "sourceUrl": "https://platform.kimi.com/docs/models",
      "asOf": "2026-08-21",
      "confidence": "official_label_only",
      "status": "research_pending",
      "maxAgeDays": 7,
      "aliasAmbiguity": "scheduled-retirement",
      "validUntil": "2026-08-31",
      "conditions": ["The official label combines input and output and the model is scheduled for retirement on 2026-08-31."]
    },
    {
      "provider": "kimi",
      "modelId": "moonshot-v1-128k",
      "aliases": [],
      "contextWindowTokens": null,
      "maxOutputTokens": null,
      "officialLabel": "128K",
      "sourceUrl": "https://platform.kimi.com/docs/models",
      "asOf": "2026-08-21",
      "confidence": "official_label_only",
      "status": "research_pending",
      "maxAgeDays": 7,
      "aliasAmbiguity": "scheduled-retirement",
      "validUntil": "2026-08-31",
      "conditions": ["The official label combines input and output and the model is scheduled for retirement on 2026-08-31."]
    },
    {
      "provider": "qwen",
      "modelId": "qwen3.7-plus",
      "aliases": [{"id": "qwen3.7-plus-2026-05-26", "moving": false}],
      "contextWindowTokens": 1000000,
      "maxOutputTokens": 131072,
      "sourceUrl": "https://help.aliyun.com/zh/model-studio/qwen3-7-plus",
      "asOf": "2026-08-21",
      "confidence": "official_direct",
      "status": "active",
      "maxAgeDays": 30,
      "aliasAmbiguity": "regional-suffixes-excluded",
      "conditions": ["Regional suffixes require separate official entries."]
    },
    {
      "provider": "qwen",
      "modelId": "qwen3.7-max",
      "aliases": [
        {"id": "qwen3.7-max-2026-06-08", "moving": false},
        {"id": "qwen3.7-max-2026-05-20", "moving": false},
        {"id": "qwen3.7-max-2026-05-17", "moving": false}
      ],
      "contextWindowTokens": 1000000,
      "maxOutputTokens": 65536,
      "sourceUrl": "https://help.aliyun.com/en/model-studio/qwen3-7-max",
      "asOf": "2026-08-21",
      "confidence": "official_direct",
      "status": "active",
      "maxAgeDays": 30,
      "aliasAmbiguity": "explicit-snapshots-only",
      "conditions": ["Only explicitly enumerated snapshots are matched."]
    },
    {
      "provider": "qwen",
      "modelId": "qwen3.7-flash",
      "aliases": [{"id": "qwen3.7-flash-2026-07-15", "moving": false}],
      "contextWindowTokens": 1000000,
      "maxOutputTokens": 65536,
      "sourceUrl": "https://help.aliyun.com/zh/model-studio/vision-model",
      "asOf": "2026-08-21",
      "confidence": "official_direct",
      "status": "active",
      "maxAgeDays": 30,
      "aliasAmbiguity": "none",
      "conditions": []
    },
    {
      "provider": "qwen",
      "modelId": "qwen3-coder-plus",
      "aliases": [{"id": "qwen3-coder-plus-2025-09-23", "moving": false}],
      "contextWindowTokens": 1000000,
      "maxOutputTokens": 65536,
      "sourceUrl": "https://help.aliyun.com/zh/model-studio/qwen3-coder-plus",
      "asOf": "2026-08-21",
      "confidence": "official_direct",
      "status": "active",
      "maxAgeDays": 30,
      "aliasAmbiguity": "none",
      "conditions": []
    }
  ]
}
'''
